language: python
python:
  - "3.6"
branches:
  only:
    - main
    - dev
    - CV-29
    - snmp-automation
addons:
  sonarcloud:
    organization: "cdot-cv"
    token: ${SONAR_TOKEN}
script:
  - coverage erase
  - coverage run -m pytest 'tests/'
  - coverage xml -i    
  - sonar-scanner
